### ISSUE TITLE
Please `dub upgrade` and tag new version

### ISSUE THREAD

**Issue by veelo** [MartinNowak/scod#13]
Documentation fails to build due to old `vibe-d` not building under newest `dmd`, which is due to a dependency of `scod` on an old `ddox`.

https://github.com/vibe-d/vibe.d/issues/2058#issuecomment-380398901

**Comment by MartinNowak** [comment]
Just tagged 0.4.4 yesterday @veelo.

**Comment by veelo** [comment]
Thanks! (I am watching you right now on the live stream :-))
