### ISSUE TITLE
dub.selections.json needs update for dmd 2.081.1

### ISSUE THREAD

**Issue by veelo** [MartinNowak/scod#14]
I fail to use `scod` with dmd 2.081.1, because it causes `stdx-allocator` to be compiled in the outdated version 2.77.1, presumably because `scod`'s `dub.selections.json` pins `ddox` at version 0.16.10.

(Sorry for ranting OT, but I think `dub.selections.json` is very poorly documented, I don't understand its purpose and I understand even less the advantage of having it under version control. It's causing nothing but problems if you want to use a recent compiler... But that's not your fault.)

**Comment by MartinNowak** [comment]
> (Sorry for ranting OT, but I think dub.selections.json is very poorly documented, I don't understand its purpose and I understand even less the advantage of having it under version control. It's causing nothing but problems if you want to use a recent compiler... But that's not your fault.)

It's used to lock dependencies to exact versions so you are able to rebuild binaries.
Might be worth an experiment to keep scod's dependencies a bit looser, by only using the fuzzy version dependencies.

On the downside it means that people using the same version of scod might be affected by different bugs in dependencies, so bug reporting gets more troublesome.

**Comment by MartinNowak** [comment]
Resolved by #16
