### ISSUE TITLE
return false in toggleTree

### ISSUE THREAD

**Issue by henrygouk** [MartinNowak/scod#9]
Is there a reason `toggleTree` in `scod.js`/`script.min.js` returns false? This prevents users from being able to navigate to pages corresponding to `package.d` files, as it will instead just collapse/expand the tree viewer.

**Comment by MartinNowak** [comment]
Fixed :).
Package modules simply didn't yet exist when I wrote this tool.

**Comment by henrygouk** [comment]
Awesome, thanks!
